Preorder = [
    ["", ""], 
    ["-", "T"], 
    ["-", "M"], 
    ["-", "O"], 
    ["-", "SS"], 
    ["", "OO"], 
    [".", "G"], 
    ["-", "Q"], 
    [".", "Z"], 
    [".", "N"], 
    ["-", "K"], 
    ["-", "Y"],
    [".", "C"],
    [".", "D"],
    ["-", "X"],
    [".", "B"],
    [".", "E"],
    ["-", "A"],
    ["-", "W"],
    ["-", "J"],
    [".", "P"],
    [".", "R"],
    ["-", "AA"],
    [".", "L"],
    [".", "I"],
    ["-", "U"],
    ["-", "UU"],
    [".", "F"],
    [".", "S"],
    ["-", "V"],
    [".", "H"],
]
Inorder = [
    ["-", "SS"],
    ["-", "O"],
    [".", "OO"],
    ["-", "M"],
    ["-", "Q"],
    [".", "G"],
    [".", "Z"],
    ["-", "T"],
    ["-", "Y"],
    ["-", "K"],
    [".", "C"],
    [".", "N"],
    ["-", "X"],
    [".", "D"],
    [".", "B"],
    ["", ""],
    ["-", "J"],
    ["-", "W"],
    [".", "P"],
    ["-", "A"],
    ["-", "AA"],
    [".", "R"],
    [".", "L"],
    ["-", "UU"],
    ["-", "U"],
    [".", "F"],
    [".", "I"],
    ["-", "V"],
    [".", "S"],
    [".", "H"],    
]